baseurl = "https://github.com/caimiao0714/me"
title = "Miao Cai | 蔡苗"
author = "Miao Cai"
canonifyurls = true
languagecode = "en"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
theme = "hugo-black-and-light-theme"
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Miao's blog"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "/post/"
[[menu.main]]
    name = "Projects"
    url  = "/post/"
[[menu.main]]
    name = "Resume"
    url  = "/post/"

